// Code generated by goctl. DO NOT EDIT.
// Source: action.proto

package actionrpc

import (
	"context"

	"TokTik/app/action/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FollowReq  = pb.FollowReq
	FollowResp = pb.FollowResp

	Actionrpc interface {
		Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
	}

	defaultActionrpc struct {
		cli zrpc.Client
	}
)

func NewActionrpc(cli zrpc.Client) Actionrpc {
	return &defaultActionrpc{
		cli: cli,
	}
}

func (m *defaultActionrpc) Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	client := pb.NewActionrpcClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}
