#app:
name: "web_app"
mode: "dev"
port: 8081
version: 1.0
log:
  level: "debug"
  file_name: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
  mode: "dev"
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "qiniu_video"
  max_open_conns: 100
  max_idle_conns: 30
  max_life_time: 600
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""
  pool_size: 50
  min_idle_conns: 20
qiniu_cloud:
  bucket: "qiniu-video-y"
  fops: "avthumb/m3u8/segtime/10/ab/128k/ar/44100/acodec/libfaac/r/30/vb/640k/vcodec/libx264/stripmeta/0"
  accessKey: "-e5YcpxbTuZ680KgPG-ne-SWiknDZ3FvT56Q75qZ"
  secretKey: "Q90f2hiU-1_As9q9nclmCVMihJR6tSczCpWreLlG"
  base: "http://s3hk0nelw.bkt.clouddn.com"
  expires: 604800

