// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"TokTik/app/video/rpc/cmd/internal/logic"
	"TokTik/app/video/rpc/cmd/internal/svc"
	"TokTik/app/video/rpc/cmd/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServer) Upload(ctx context.Context, in *video.UploadReq) (*video.UploadResp, error) {
	l := logic.NewUploadLogic(ctx, s.svcCtx)
	return l.Upload(in)
}
