// Code generated by goctl. DO NOT EDIT.
package types

type GetUserInfoReq struct {
	Id int64 `path:"id"`
}

type GetUserInfoResp struct {
	Status  int    `json:"status"`
	Data    User   `json:"data"`
	Message string `json:"message"`
	Error   string `json:"error"`
}

type User struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Avatar   string `json:"avatar"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Avatar   string `json:"avatar"`
}

type RegisterResp struct {
	Status  int    `json:"status"`
	Data    string `json:"data"`
	Message string `json:"message"`
	Error   string `json:"error"`
}

type Data struct {
	User  User   `json:"user"`
	Token string `json:"token"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	Status  int    `json:"status"`
	Data    Data   `json:"data"`
	Message string `json:"message"`
	Error   string `json:"error"`
}

type GetFollowingsRequest struct {
	UserId int64 `path:"id"`
}

type GetFollowingsResponse struct {
	Status  int    `json:"status"`
	Data    []User `json:"data"`
	Message string `json:"message"`
	Error   string `json:"error"`
}

type GetFansRequest struct {
	UserId int64 `path:"id"`
}

type GetFansResponse struct {
	Status  int    `json:"status"`
	Data    []User `json:"data"`
	Message string `json:"message"`
	Error   string `json:"error"`
}
