// Code generated by goctl. DO NOT EDIT!

package users

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheQiniuTiktokUsersIdPrefix    = "cache:qiniuTiktok:users:id:"
	cacheQiniuTiktokUsersEmailPrefix = "cache:qiniuTiktok:users:email:"
)

type (
	usersModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Users) error

		FindOne(ctx context.Context, id int64) (*Users, error)
		FindOneByEmail(ctx context.Context, email string) (*Users, error)
		Update(ctx context.Context, tx *gorm.DB, data *Users) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultUsersModel struct {
		gormc.CachedConn
		table string
	}

	Users struct {
		Id        int64          `gorm:"column:id"`
		CreatedAt sql.NullTime   `gorm:"column:created_at"`
		UpdatedAt sql.NullTime   `gorm:"column:updated_at"`
		DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;index"`
		Username  string         `gorm:"column:username"` // 用户名
		Avatar    sql.NullString `gorm:"column:avatar"`   // 头像
		Email     string         `gorm:"column:email"`    // 邮箱
		Password  string         `gorm:"column:password"` // 密码
	}
)

func (Users) TableName() string {
	return "`users`"
}

func newUsersModel(conn *gorm.DB, c cache.CacheConf) *defaultUsersModel {
	return &defaultUsersModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`users`",
	}
}

func (m *defaultUsersModel) Insert(ctx context.Context, tx *gorm.DB, data *Users) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultUsersModel) FindOne(ctx context.Context, id int64) (*Users, error) {
	qiniuTiktokUsersIdKey := fmt.Sprintf("%s%v", cacheQiniuTiktokUsersIdPrefix, id)
	var resp Users
	err := m.QueryCtx(ctx, &resp, qiniuTiktokUsersIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Users{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByEmail(ctx context.Context, email string) (*Users, error) {
	qiniuTiktokUsersEmailKey := fmt.Sprintf("%s%v", cacheQiniuTiktokUsersEmailPrefix, email)
	var resp Users
	err := m.QueryRowIndexCtx(ctx, &resp, qiniuTiktokUsersEmailKey, m.formatPrimary, func(conn *gorm.DB, v interface{}) (interface{}, error) {
		if err := conn.Model(&Users{}).Where("`email` = ?", email).Take(&resp).Error; err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) Update(ctx context.Context, tx *gorm.DB, data *Users) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultUsersModel) getCacheKeys(data *Users) []string {
	if data == nil {
		return []string{}
	}
	qiniuTiktokUsersEmailKey := fmt.Sprintf("%s%v", cacheQiniuTiktokUsersEmailPrefix, data.Email)
	qiniuTiktokUsersIdKey := fmt.Sprintf("%s%v", cacheQiniuTiktokUsersIdPrefix, data.Id)
	cacheKeys := []string{
		qiniuTiktokUsersEmailKey, qiniuTiktokUsersIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultUsersModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Users{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultUsersModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultUsersModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheQiniuTiktokUsersIdPrefix, primary)
}

func (m *defaultUsersModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Users{}).Where("`id` = ?", primary).Take(v).Error
}
