// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"TokTik/app/user/cmd/rpc/internal/logic"
	"TokTik/app/user/cmd/rpc/internal/svc"
	"TokTik/app/user/cmd/rpc/pb"
)

type UserrpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserrpcServer
}

func NewUserrpcServer(svcCtx *svc.ServiceContext) *UserrpcServer {
	return &UserrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserrpcServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserrpcServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserrpcServer) GenerateToken(ctx context.Context, in *pb.GenerateTokenReq) (*pb.GenerateTokenResp, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

func (s *UserrpcServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserrpcServer) GetFollowings(ctx context.Context, in *pb.GetFollowingsReq) (*pb.GetFollowingsResp, error) {
	l := logic.NewGetFollowingsLogic(ctx, s.svcCtx)
	return l.GetFollowings(in)
}

func (s *UserrpcServer) GetFans(ctx context.Context, in *pb.GetFansReq) (*pb.GetFansResp, error) {
	l := logic.NewGetFansLogic(ctx, s.svcCtx)
	return l.GetFans(in)
}
