// Code generated by goctl. DO NOT EDIT.
package types

type FollowRequest struct {
	Id int64 `json:"id"`
}

type FollowResponse struct {
	Status  int    `json:"status"`
	Data    string `json:"data"`
	Message string `json:"message"`
	Error   string `json:"error"`
}
