// Code generated by goctl. DO NOT EDIT!

package fans

import (
	"context"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheQiniuTiktokFansIdPrefix = "cache:qiniuTiktok:fans:id:"
)

type (
	fansModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Fans) error

		FindOne(ctx context.Context, id int64) (*Fans, error)
		Update(ctx context.Context, tx *gorm.DB, data *Fans) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultFansModel struct {
		gormc.CachedConn
		table string
	}

	Fans struct {
		Id     int64 `gorm:"column:id"`
		UserId int64 `gorm:"column:user_id"` // 用户id
		FanId  int64 `gorm:"column:fan_id"`  // 粉丝的id
	}
)

func (Fans) TableName() string {
	return "`fan`"
}

func newFansModel(conn *gorm.DB, c cache.CacheConf) *defaultFansModel {
	return &defaultFansModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`fan`",
	}
}

func (m *defaultFansModel) Insert(ctx context.Context, tx *gorm.DB, data *Fans) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultFansModel) FindOne(ctx context.Context, id int64) (*Fans, error) {
	qiniuTiktokFansIdKey := fmt.Sprintf("%s%v", cacheQiniuTiktokFansIdPrefix, id)
	var resp Fans
	err := m.QueryCtx(ctx, &resp, qiniuTiktokFansIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Fans{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFansModel) Update(ctx context.Context, tx *gorm.DB, data *Fans) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultFansModel) getCacheKeys(data *Fans) []string {
	if data == nil {
		return []string{}
	}
	qiniuTiktokFansIdKey := fmt.Sprintf("%s%v", cacheQiniuTiktokFansIdPrefix, data.Id)
	cacheKeys := []string{
		qiniuTiktokFansIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultFansModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Fans{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultFansModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultFansModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheQiniuTiktokFansIdPrefix, primary)
}

func (m *defaultFansModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Fans{}).Where("`id` = ?", primary).Take(v).Error
}
