// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"TokTik/app/video/api/cmd/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/upload_video",
				Handler: UploadVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/delete_video",
				Handler: DeleteVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/star_video",
				Handler: StarVideoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/video"),
	)
}
