// Code generated by goctl. DO NOT EDIT.
package types

type UploapReq struct {
	Title string `form:"title"`
	Kind  uint   `form:"kind"`
}

type UploapResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type DeleteReq struct {
	Id int `json:"id"`
}

type DeleteResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
